languageCode = "en-us"
title = "Ren Jie"
baseurl = "https://www.renjietan.me/"
theme = "prologue"

[params]
  name = "Ren Jie"
  description = "Computer Vision Engineer"
  copyright = "Ren Jie 2020"

[[params.social]]
  medium = "github"
  icon = "fab fa-github"
  link = "https://github.com/notha99y"

[[params.social]]
  medium = "linkedin"
  icon = "fab fa-linkedin"
  link = "https://www.linkedin.com/in/renjietan/"

[[params.social]]
  medium = "twitter"
  icon = "fab fa-twitter"
  link = "https://twitter.com/rahjaytee"

[[params.social]]
  medium = "email"
  icon = "fas fa-envelope"
  link = "mailto:renjie.tan91@gmail.com"

# [[params.social]]
#   medium = "facebook"
#   icon = "facebook"
#   link = "#"

# [[params.social]]
#   medium = "dribbble"
#   icon = "dribbble"
#   link = "#"

# Portfolio column one

# [[params.portfolio1]]
#   title = "Breaking Down Mean Average Precision (mAP)"
#   alt = ""
#   source = "img/TDS/mAP.jpeg"
#   url = "https://towardsdatascience.com/breaking-down-mean-average-precision-map-ae462f623a52"



# # Portfolio column two

[[params.portfolio2]]
  title = "Breaking Down Mean Average Precision (mAP)"
  alt = ""
  source = "img/TDS/mAP.jpeg"
  url = "https://towardsdatascience.com/breaking-down-mean-average-precision-map-ae462f623a52"

[[params.portfolio1]]
  title = "A Starter Pack to Exploratory Data Analysis with Python, pandas, seaborn, and scikit-learn"
  alt = ""
  source = "img/TDS/EDA.jpeg"
  url = "https://towardsdatascience.com/a-starter-pack-to-exploratory-data-analysis-with-python-pandas-seaborn-and-scikit-learn-a77889485baf"

[[params.portfolio3]]
  title = "Breaking Down Mean Average Precision (mAP)"
  alt = ""
  source = "img/TDS/HAR.jpeg"
  url = "https://towardsdatascience.com/6-steps-to-quickly-train-a-human-action-classifier-with-validation-accuracy-of-over-80-655fcb8781c5"



# [[params.portfolio2]]
#   title = "Magna Nullam"
#   alt = ""
#   source = "img/pic04.jpg"
#   url = "#"

# [[params.portfolio2]]
#   title = "Natoque Vitae"
#   alt = ""
#   source = "img/pic05.jpg"
#   url = "#"

# # # Portfolio column 3

# [[params.portfolio3]]
#   title = "Dolor Penatibus"
#   alt = ""
#   source = "img/pic06.jpg"
#   url = "#"

# [[params.portfolio3]]
#   title = "Orci Convallis"
#   alt = ""
#   source = "img/pic07.jpg"
#   url = "#"

[[params.techstack]]
  medium = "python"
  icon = "python"
  link = ""

[[params.techstack]]
  medium = "git"
  icon = "git"
  link = ""


[[params.techstack]]
  medium = "linux"
  icon = "linux"
  link = ""

  [[params.techstack]]
  medium = "docker"
  icon = "docker"
  link = ""